# Spring properties
spring:
  application:
     name: demo-web  # Service registers under this name

# Discovery Server Access
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
